### ISSUE TITLE
prometheus health check

### ISSUE THREAD

**Issue by lmzxqtom** [sratcliffe/cephmetrics#2]
In the docker compose file, prometheus has a health check:

```
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9090"]
        interval: 30s
        timeout: 10s
        retries: 5
```
Seems that this is run inside the docker contain, so prom/prometheus:v2.1.0 needs to have curl installed.
